# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Permute a Bernoulli treatment vector
#' @description This function permutes a Bernoulli treatment vector of length n with s entries equal to 1.
#' @param n the sample size
#' @param s the number of entries equal to 1
#' @param B the number of WOR samples to generate
#' @noRd
fisher_yates_samlper <- function(n, s, B) {
    .Call(`_camp_fisher_yates_samlper`, n, s, B)
}

run_low_level_test_full_v4 <- function(y, mu, a, w, D, trt_idxs, n_trt, use_all_cells, synthetic_idxs, B1, B2, B3, fit_parametric_curve, return_resampling_dist, side_code) {
    .Call(`_camp_run_low_level_test_full_v4`, y, mu, a, w, D, trt_idxs, n_trt, use_all_cells, synthetic_idxs, B1, B2, B3, fit_parametric_curve, return_resampling_dist, side_code)
}

