# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Permute a Bernoulli treatment vector
#' @description This function permutes a Bernoulli treatment vector of length n with s entries equal to 1.
#' @param n the sample size
#' @param s the number of entries equal to 1
#' @param B the number of WOR samples to generate
#' @noRd
fisher_yates_samlper <- function(n, s, B) {
    .Call(`_camp_fisher_yates_samlper`, n, s, B)
}

run_test_resid_stat_binary_cpp <- function(trt_idxs, synthetic_idxs, resids, s, B, side, adaptive, B_0, p_thresh, return_null_distribution) {
    .Call(`_camp_run_test_resid_stat_binary_cpp`, trt_idxs, synthetic_idxs, resids, s, B, side, adaptive, B_0, p_thresh, return_null_distribution)
}

run_test_score_stat_binary_cpp <- function(trt_idxs, synthetic_idxs, a, w, D, s, B, side, adaptive, B_0, p_thresh, return_null_distribution) {
    .Call(`_camp_run_test_score_stat_binary_cpp`, trt_idxs, synthetic_idxs, a, w, D, s, B, side, adaptive, B_0, p_thresh, return_null_distribution)
}

compute_empirical_p_value <- function(null_statistics, z_orig, side) {
    .Call(`_camp_compute_empirical_p_value`, null_statistics, z_orig, side)
}

